/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package createdpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ID
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDemo
     */
    public Update() {
        initComponents();
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stud","root","root");
            Statement pstmt = conn.createStatement();
            String sql = "select * from Registration";
            ResultSet rs = pstmt.executeQuery(sql);
            
            while(rs.next()){
                
                String ID = String.valueOf(rs.getInt("RollNo"));
                String FN = rs.getString("FirstName");
                String LN = rs.getString("LastName");
                String CL = rs.getString("Class");
                String GN = rs.getString("Gender");
                String CO = rs.getString("Contact");
                String AD = rs.getString("Address");
                String DOB = rs.getString("DOB");
                
                String[] tbData = {ID,FN,LN,CL,GN,CO,AD,DOB};
                
                DefaultTableModel tb1Model = (DefaultTableModel) tb1.getModel();
                
                tb1Model.addRow(tbData);
            }   
            conn.close();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rno1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fn1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ln1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cl1 = new javax.swing.JTextField();
        gn1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        co1 = new javax.swing.JTextField();
        ad1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dob1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 153, 51));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Update");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(896, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 0, 1360, 58);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("                    Roll no.");
        jLabel9.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 100, 171, 30);

        rno1.setBackground(new java.awt.Color(153, 153, 153));
        rno1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rno1ActionPerformed(evt);
            }
        });
        jPanel1.add(rno1);
        rno1.setBounds(200, 100, 182, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("              First Name");
        jLabel10.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 140, 216, 25);

        fn1.setBackground(new java.awt.Color(153, 153, 153));
        fn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(fn1);
        fn1.setBounds(200, 140, 182, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("              Last Name");
        jLabel11.setToolTipText("");
        jLabel11.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 180, 151, 25);

        ln1.setBackground(new java.awt.Color(153, 153, 153));
        ln1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(ln1);
        ln1.setBounds(200, 180, 182, 25);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("                       Class");
        jLabel12.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 220, 151, 25);

        cl1.setBackground(new java.awt.Color(153, 153, 153));
        cl1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cl1);
        cl1.setBounds(200, 220, 182, 25);

        gn1.setBackground(new java.awt.Color(153, 153, 153));
        gn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(gn1);
        gn1.setBounds(200, 260, 182, 25);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("                   Gender");
        jLabel13.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 260, 130, 25);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("         Contact no.");
        jLabel14.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 300, 130, 25);

        co1.setBackground(new java.awt.Color(153, 153, 153));
        co1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(co1);
        co1.setBounds(200, 300, 182, 25);

        ad1.setBackground(new java.awt.Color(153, 153, 153));
        ad1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(ad1);
        ad1.setBounds(200, 340, 182, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("              Address");
        jLabel16.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 340, 130, 25);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("                  D.O.B");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 380, 191, 25);

        dob1.setBackground(new java.awt.Color(153, 153, 153));
        dob1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob1ActionPerformed(evt);
            }
        });
        jPanel1.add(dob1);
        dob1.setBounds(200, 380, 182, 25);

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createdpackage/Save-icon.png"))); // NOI18N
        jButton5.setText("Update");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(20, 450, 103, 40);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createdpackage/search (2).png"))); // NOI18N
        jButton1.setText("Searching");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 450, 103, 40);

        jPanel9.setBackground(new java.awt.Color(255, 153, 51));

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setText("Previous");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(1487, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(-300, 610, 1660, 60);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createdpackage/delete_16x16.gif"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 450, 103, 40);

        tb1.setBackground(new java.awt.Color(153, 153, 153));
        tb1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tb1.setForeground(new java.awt.Color(255, 255, 255));
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RollNo", "First Name", "Last Name", "Class", "Gender", "Contact", "Address", "DOB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tb1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(400, 70, 900, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1312, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rno1ActionPerformed

    private void dob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try{
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stud","root","root")) {
                String sql = "update Registration set FirstName = ?, LastName = ?, Class = ?, Gender = ?, Contact = ?, Address = ?, DOB = ? where Rollno = ?";
                
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, fn1.getText());
                pstmt.setString(2, ln1.getText());
                pstmt.setInt(3, Integer.parseInt(cl1.getText()));
                pstmt.setString(4, gn1.getText());
                pstmt.setInt(5, Integer.parseInt(co1.getText()));
                pstmt.setString(6, ad1.getText());
                pstmt.setString(7, dob1.getText());
                pstmt.setInt(8, Integer.parseInt(rno1.getText()));
                
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Updated Successfully");
            }

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        dispose();
        new Update().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stud","root","root");

            String sql = "select * from Registration where Rollno = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setInt(1, Integer.parseInt(rno1.getText()));

            ResultSet rs = pstmt.executeQuery();
            if(rs.next())
            {
                fn1.setText(rs.getString("FirstName"));
                ln1.setText(rs.getString("LastName"));
                cl1.setText(rs.getString("Class"));
                gn1.setText(rs.getString("Gender"));
                co1.setText(rs.getString("Contact"));
                ad1.setText(rs.getString("Address"));
                dob1.setText(rs.getString("DOB"));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Sorry Record not found");
            }
            conn.close();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        new MainMenu().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        rno1.setText("");
        fn1.setText("");
        ln1.setText("");
        cl1.setText("");
        gn1.setText("");
        co1.setText("");
        ad1.setText("");
        dob1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad1;
    private javax.swing.JTextField cl1;
    private javax.swing.JTextField co1;
    private javax.swing.JTextField dob1;
    private javax.swing.JTextField fn1;
    private javax.swing.JTextField gn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ln1;
    private javax.swing.JTextField rno1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
